version: "3"
services:
  db:
    build: 
      context: ./storage
      dockerfile: Dockerfile
    container_name: mysql
    restart: unless-stopped
    ports:
      - 3300:3306
    command: --default-authentication-plugin=mysql_native_password
    # env_file: 
    #   .env
    environment: 
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test2
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testuser
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    ports:
      - "1337:1337"